# syntax=docker/dockerfile:1
FROM golang:1.20.5 AS build-stage

WORKDIR /app

COPY go.mod ./
COPY *.go ./
COPY Makefile ./

RUN go mod download

# RUN make build
RUN make build-docker


# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/bin/docker-golang /

EXPOSE 8080

USER nonroot:nonroot

CMD ["./docker-golang"]
